# Generated by Django 2.1.3 on 2018-12-05 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_area', models.CharField(max_length=50, verbose_name='Área de Atendimento')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria_Problema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_categoria_problema', models.CharField(max_length=50, verbose_name='Categoria Problema')),
            ],
        ),
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_abertura', models.DateTimeField(auto_now_add=True)),
                ('dt_alterado', models.DateTimeField()),
                ('dt_fechamento', models.DateTimeField()),
                ('desc_problema', models.TextField(blank=True, default='Por favor descreva o Problema Ocorrido.', verbose_name='Descricão Problema')),
                ('desc_solucao', models.TextField(blank=True, default='Por favor descreva a Solução do Problema.', verbose_name='Descricão Solução')),
                ('desc_sla_justificativa', models.TextField(blank=True, default='Por favor descreva a Justificativa para o estouro do SLA.', verbose_name='Descricão Solução')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.Area', verbose_name='Área')),
                ('categoria_problema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.Categoria_Problema', verbose_name='Categoria_problema')),
                ('criador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
        migrations.CreateModel(
            name='Problema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_problema', models.CharField(max_length=50, verbose_name='Problema')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.Area', verbose_name='Área')),
            ],
            options={
                'verbose_name': 'Problema',
                'verbose_name_plural': 'Problemas',
            },
        ),
        migrations.AddField(
            model_name='chamado',
            name='problema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.Problema', verbose_name='Problema'),
        ),
        migrations.AddField(
            model_name='categoria_problema',
            name='Problema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.Problema', verbose_name='Problema'),
        ),
    ]
