# Generated by Django 2.1.3 on 2018-12-11 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chamado',
            options={'verbose_name': 'Chamado', 'verbose_name_plural': 'Chamados'},
        ),
        migrations.AddField(
            model_name='categoria_problema',
            name='sla',
            field=models.PositiveSmallIntegerField(default=24),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='desc_sla_justificativa',
            field=models.TextField(blank=True, default='Por favor descreva a Justificativa para o estouro do SLA.', verbose_name='Descricão Estouro SLA'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='dt_alterado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='dt_fechamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
