# Generated by Django 2.1.3 on 2018-12-12 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_auto_20181211_2322'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chamado',
            options={'verbose_name': 'Chamado', 'verbose_name_plural': 'Chamados'},
        ),
    ]
