# Generated by Django 2.1.3 on 2018-12-13 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_auto_20181212_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='status_chamado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=150, verbose_name='Status Atendimento')),
            ],
            options={
                'verbose_name': 'status_chamado',
                'verbose_name_plural': 'status_chamados',
            },
        ),
        migrations.AddField(
            model_name='chamado',
            name='status_chamado',
            field=models.CharField(default='aguardando atendimento', max_length=150),
        ),
    ]
