# Generated by Django 2.1.3 on 2018-12-13 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_auto_20181213_1932'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status_chamado',
            options={'verbose_name': 'Status_Chamado', 'verbose_name_plural': 'Status_Chamados'},
        ),
        migrations.AlterField(
            model_name='chamado',
            name='status_chamado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.Status_Chamado', verbose_name='Status'),
        ),
    ]
