# Generated by Django 2.1.3 on 2018-12-17 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0010_auto_20181215_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria_problema',
            name='tipo_manutencao',
            field=models.CharField(default='suporte', max_length=50, verbose_name='Tipo Manutenção'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='status_chamado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.Status_Chamado', verbose_name='Status'),
        ),
    ]
