# Generated by Django 2.1.3 on 2018-12-20 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0012_auto_20181220_1847'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Unidade',
        ),
        migrations.AddField(
            model_name='chamado',
            name='local',
            field=models.CharField(choices=[('LOCAL', 'Selecione o Local'), ('LJAREADEVENDAS', 'Loja - Àrea de Vendas'), ('LJCPD', 'Loja - CPD'), ('LJTESOURARIA', 'Loja - Tesouraria'), ('LJGERENCIA', 'Loja - Gerência'), ('LJDP', 'Loja - Departamento Pessoal'), ('LJDEPOSITO', 'Loja Deposito'), ('LJACOUGUE', 'Loja Açougue'), ('LJPADARIA', 'Loja - Padaria'), ('LJSALGADOS', 'Loja - Salgados'), ('LJACOUGUE', 'Loja - Açougue'), ('LJHORTIFRUTI', 'Loja - Hortifruti'), ('LJLATICINIOS', 'Loja - Laticínios')], default='LOCAL', max_length=100, verbose_name='Local'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='unidade',
            field=models.CharField(choices=[('UNIDADE', 'Selecione a Unidade'), ('FL01', 'Filial 01'), ('FL02', 'Filial 02'), ('FL03', 'Filial 03'), ('FL04', 'Filial 04'), ('FL05', 'Filial 05'), ('FL06', 'Filial 06'), ('FL07', 'Filial 07'), ('FL08', 'Filial 08'), ('FL09', 'Filial 09'), ('FL10', 'Filial 10'), ('FL11', 'Filial 11'), ('FL12', 'Filial 12'), ('FL13', 'Filial 13'), ('FL15', 'Filial 15'), ('FL16', 'Filial 16'), ('CS', 'Carga Seca'), ('CF', 'Carga Fria'), ('CTT', 'Citta'), ('DWNT', 'Downtown')], default='UNIDADE', max_length=100, verbose_name='Unidade'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='status_chamado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.Status_Chamado', verbose_name='Status'),
        ),
    ]
