# Generated by Django 2.1.3 on 2018-12-20 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0013_auto_20181220_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='ramal',
            field=models.CharField(default='4392', max_length=15),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='local',
            field=models.CharField(choices=[('LOCAL', 'LOCAL'), ('Àrea de Vendas', 'Àrea de Vendas'), ('CPD', 'CPD'), ('Tesouraria', 'Tesouraria'), ('Gerência', 'Gerência'), ('Departamento Pessoal', 'Departamento Pessoal'), ('Deposito', 'Deposito'), ('Açougue', 'Açougue'), ('Padaria', 'Padaria'), ('Salgados', 'Salgados'), ('Açougue', 'Açougue'), ('Hortifruti', 'Hortifruti'), ('Laticínios', 'Laticínios')], default='LOCAL', max_length=100, verbose_name='Local'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='status_chamado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.Status_Chamado', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='unidade',
            field=models.CharField(choices=[('UNIDADE', 'Selecione a Unidade'), ('FILIAL 01', 'FILIAL 01'), ('FILIAL 02', 'FILIAL 02'), ('FILIAL 03', 'FILIAL 03'), ('FILIAL 04', 'FILIAL 04'), ('FILIAL 05', 'FILIAL 05'), ('FILIAL 06', 'FILIAL 06'), ('FILIAL 07', 'FILIAL 07'), ('FILIAL 08', 'FILIAL 08'), ('FILIAL 09', 'FILIAL 09'), ('FILIAL 10', 'FILIAL 10'), ('FILIAL 11', 'FILIAL 11'), ('FILIAL 12', 'FILIAL 12'), ('FILIAL 13', 'FILIAL 13'), ('FILIAL 15', 'FILIAL 15'), ('FILIAL 16', 'FILIAL 16'), ('CARGA SECA', 'CARGA SECA'), ('CARGA SECA', 'CARGA SECA'), ('CITTA', 'CITTA'), ('DOWNTOWN', 'DOWNTOWN')], default='UNIDADE', max_length=100, verbose_name='Unidade'),
        ),
    ]
